### ISSUE TITLE
Processing fails when calling out

### ISSUE THREAD

**Issue by jc064522** [gchq/stroom-auth#52]
Unable to get token for user:

```
stroom.auth.service.ApiException

java.lang.RuntimeException: Error sending request DocRef{type='Index', uuid='a6e2fc24-d312-4663-aa1d-18f5b6be0d33', name='someIndex'} to /dataSource
    at stroom.datasource.RemoteDataSourceProvider.post(RemoteDataSourceProvider.java:106)
    at stroom.datasource.RemoteDataSourceProvider.getDataSource(RemoteDataSourceProvider.java:65)
    at stroom.dashboard.server.FetchExpressionFieldsHandler.lambda$exec$0(FetchExpressionFieldsHandler.java:50)
    at java.util.Optional.map(Optional.java:215)
    at stroom.dashboard.server.FetchExpressionFieldsHandler.exec(FetchExpressionFieldsHandler.java:49)
    at stroom.dashboard.server.FetchExpressionFieldsHandler.exec(FetchExpressionFieldsHandler.java:30)
    at stroom.task.server.AbstractTaskHandler.exec(AbstractTaskHandler.java:31)
    at sun.reflect.GeneratedMethodAccessor154.invoke(Unknown Source)
    at stroom.dispatch.server.DispatchServiceImpl.exec(DispatchServiceImpl.java:104)
    at sun.reflect.GeneratedMethodAccessor280.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)#
    at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Unable to get the user's token from the Token service! User was: admin
    at stroom.apiclients.AuthenticationServiceClients.getTokenFromTokenService(AuthenticationServiceClients.java:131)
    at stroom.apiclients.AuthenticationServiceClients.getUsersApiToken(AuthenticationServiceClients.java:76)
    at stroom.datasource.RemoteDataSourceProvider.post(RemoteDataSourceProvider.java:87)
    ... 100 more
Caused by: stroom.auth.service.ApiException: Unauthorized
    at stroom.auth.service.ApiClient.handleResponse(ApiClient.java:1046)
    at stroom.auth.service.ApiClient.execute(ApiClient.java:969)
    at stroom.auth.service.api.ApiKeyApi.searchWithHttpInfo(ApiKeyApi.java:835)
    at stroom.auth.service.api.ApiKeyApi.search(ApiKeyApi.java:821)
    at stroom.apiclients.AuthenticationServiceClients.getTokenFromTokenService(AuthenticationServiceClients.java:118)
    ... 102 more
```

**Comment by jc064522** [comment]
Fixed locations and checks.
